export const ADD_ABOUT = 'ADD_ABOUT';
export const ABOUT_LOADING = 'ABOUT_LOADING';
export const ABOUT_FAILED = 'ABOUT_FAILED';

export const QUALIFICATIONS_LOADING = 'QUALIFICATIONS_LOADING';
export const ADD_QUALIFICATIONS = 'ADD_QUALIFICATIONS';
export const QUALIFICATIONS_FAILED = 'QUALIFICATIONS_FAILED';

export const SKILLS_LOADING = 'SKILLS_LOADING';
export const ADD_SKILLS = 'ADD_SKILLS';
export const SKILLS_FAILED = 'SKILLS_FAILED';